base_link:
  sensor_kit_base_link:
    x: 0.0
    y: 0.0
    z: 0
    roll: 0
    pitch: 0
    yaw: 0
  # velodyne_rear_base_link:
  #   x: -0.358
  #   y: 0.0
  #   z: 1.631
  #   roll: -0.02
  #   pitch: 0.7281317
  #   yaw: 3.141592
    # velodyne_top_base_link:
    #   x: 0.8
    #   y: 0.0
    #   z: 100.831
    #   roll: 0
    #   pitch: 0
    #   yaw: 0
